# -------------------------------------------------------
# Docker Compose
# -------------------------------------------------------
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnet
    depends_on:
      - app
      
  app:
    build: ./app
    hostname: application
    expose:
      - 5000
    networks:
      - appnet
    volumes:
      - ./app:/app

networks:
  appnet: